Added Plone newsletter sign up in footer #182
plone/plone.org pull request #185
Opened 2024-12-01 17:26 UTC by Adityaadpandey

Added a Plone newsletter sign up page link to Plone.org in the footer #182

2024-12-01 22:06 UTC, stevepiercy requested changes

2024-12-01 22:06 UTC, stevepiercy commented on frontend/src/customizations/volto/components/theme/Footer/Footer.jsx
> +                    <a href="https://plone.org/news-and-events/join-the-plone-newsletter">
The link is relative to the site root.

```suggestion
                    <a href="/news-and-events/join-the-plone-newsletter">
```

2024-12-01 22:08 UTC, stevepiercy commented
@Adityaadpandey please read and follow [Contributing](https://6.docs.plone.org/contributing/index.html). We cannot merge this PR without your signed Plone Contributor Agreement. Thank you!

2024-12-02 02:35 UTC, Adityaadpandey commented
Thank you for the help, as now i read and signed the contract.

2024-12-02 06:10 UTC, stevepiercy approved these changes

2024-12-02 06:11 UTC, stevepiercy commented
@Adityaadpandey we need to wait for your Plone Contributor Agreement to get approved, then we can merge. Thank you for your contribution!

2024-12-09 10:54 UTC, Adityaadpandey commented
The request for contribution on plane has been approved

2024-12-09 11:02 UTC, stevepiercy commented
@Adityaadpandey it appears that you did not complete the process by accepting the invitation.

2024-12-09 11:10 UTC, Adityaadpandey commented
Sorry for the inconvenience now i have done that is there anything else left to do

2024-12-09 11:13 UTC, stevepiercy commented
Needs review by @plone/marketing-communications team.

2024-12-09 18:31 UTC, tkimnguyen commented
This is a nice idea. Thank you @Adityaadpandey

2024-12-09 18:33 UTC, davisagli requested changes

2024-12-09 18:33 UTC, davisagli commented on frontend/src/customizations/volto/components/theme/Footer/Footer.jsx
> +                    </a>
@Adityaadpandey Please update the link to use the Link component like the other internal links in this menu. This way the navigation happens via the Volto router and doesn't need a full page reload.

2024-12-09 18:40 UTC, davisagli commented on frontend/src/customizations/volto/components/theme/Footer/Footer.jsx
> +                    <Link href="/news-and-events/join-the-plone-newsletter">
@Adityaadpandey Look carefully -- the `Link` component uses `to` instead of `href`

2024-12-09 18:41 UTC, Adityaadpandey reviewed
made the changes as asked for the use  Link component so doesn't need a full page reload.

2024-12-09 18:44 UTC, davisagli approved these changes

2024-12-09 18:44 UTC, merged

2024-12-10 11:11 UTC, astridjuizi reviewed
Looks good and in the correct position.

2024-12-10 14:52 UTC, fredvd commented
LGTM, @astridjuizi also checked the testing site.  I'll create a release this evening to update the live site.  I see there are also some other changes on main that might not have landed in the changelog, these will also go live, I'll try to update the changelog.

2024-12-10 21:48 UTC, fredvd commented
Pushed to live plone.org in release 1.0.17.